# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AudioRecorder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AudioRecorder
  pod 'SnapKit'

  target 'AudioRecorderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AudioRecorderUITests' do
    # Pods for testing
  end

end
